import type { ContentBlock, TextSegment } from "../src/types";
export type ArticleBlock = Omit<ContentBlock, "id">;
export type LayoutResult = { blocks: ArticleBlock[]; notice?: string };
export const sampleArticle: string;
export function createBlocksFromText(input: string): ArticleBlock[];
export function formatArticle(input: string): LayoutResult;
export function layoutPreservesSource(blocks: ArticleBlock[], source: string): boolean;
export function validateLayoutResult(blocks: ArticleBlock[], source: string): LayoutResult;
export function makeBlock(type: ContentBlock["type"], text?: string, highlight?: boolean, underline?: boolean, segments?: TextSegment[]): ArticleBlock;
export function blocksToMarkdown(blocks: ArticleBlock[]): string;
export function normalizeTextSegments(segments?: TextSegment[]): TextSegment[] | undefined;
export function textFromSegments(segments: TextSegment[]): string;
export function applyRuleBasedEmphasis(blocks: ArticleBlock[]): ArticleBlock[];
